name: ci

on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Testing
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: |
            project update
            do go_test

      - name: Build
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: |
            project update
            do go_build
