name: dagger/docker

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DAGGER_LOGLEVEL: "debug"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dagger
        uses: dagger/dagger-for-github@v3
        with:
          install-only: true

      - name: Dagger project update
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
        run: dagger project update

      - name: Docker build
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
        run: do docker_build --log-format plain --log-level ${DAGGER_LOGLEVEL}

      - name: Docker push
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
        run: do docker_push --log-format plain --log-level ${DAGGER_LOGLEVEL}
