name: docker

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Docker build
        uses: dagger/dagger-for-github@v3
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          version: 0.2
          cmds: |
            project update
            do docker_build

      - name: Docker push
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: |
            project update
            do docker_push
